### ISSUE TITLE
Number of rollback snapshots

### ISSUE THREAD

**Issue by bronze** [mathielo/dst-dedicated-server#14]
Hi

Ive been following your config (not on docker but still, your config is much more up-to-date than those steam FAQs) and under cluster.ini ive just realized theres no max_snapshots configuration.
Id like to propose as per [](https://forums.kleientertainment.com/forums/topic/64552-dedicated-server-settings-guide/)

> cluster.ini
> ```
> [MISC]
> ; defaults to 6
> max_snapshots = 6 
> ```

cheers

**Comment by mathielo** [comment]
Hey @bronze, awesome suggestion! You are more than welcome to open a PR for it if you'd like :nerd_face: Otherwise I'll make sure to add it later on.

**Comment by mathielo** [comment]
Added in #15 :sunglasses:
