### ISSUE TITLE
How to Connect to the server?

### ISSUE THREAD

**Issue by kl456123** [mathielo/dst-dedicated-server#18]
Ubuntu 18.04
Local/own compute, LAN(wifi enviroment)
I dont modify the other configuration other than passwd and server's name.After I run `docker-compose up -d`, two dockers are ok. But I cannot find them in steam server anywhere(in steam internet or LAN)
If I run `./dontstarve_dedicated_server_nullrenderer -cluster ${cluster_name} -shared Master`
It works well and I can find it in steam server lists in LAN.
Please help me thanks, I seldom use docker.

**Comment by mathielo** [comment]
Hey @kl456123 sorry for the late reply. 

Did you uncomment the `offline_server` line in [`DSTClusterConfig/cluster.ini`](
https://github.com/mathielo/dst-dedicated-server/blob/master/DSTClusterConfig/cluster.ini#L51) and set it to `true`? That is what determines whether yours is an "Online" or "LAN" server. 

If you didn't uncomment it, it should be available in the list of online servers as long as you properly [created a cluster token](https://github.com/mathielo/dst-dedicated-server/blob/master/docs/ClusterToken.md). If you didn't, then your sever failed to register to Klei's servers and won't be listed in the lobby, show this message in the logs:

```
dst_master    | [00:00:02]: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
dst_master    | [00:00:02]: !!!! Your Server Will Not Start !!!!
dst_master    | [00:00:02]: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by kl456123** [comment]
Thanks first, I will try it then
