### ISSUE TITLE
Server shows ping as "???"

### ISSUE THREAD

**Issue by acklackl** [mathielo/dst-dedicated-server#2]
server is running and i can see it, but ping is showing "???" not sure what to do...

**Comment by mathielo** [comment]
Is is actually a known issue. Check out [this thread in Klei's Forums](https://forums.kleientertainment.com/topic/86109-ping-on-the-server-is-shown-as/?tab=comments#comment-989707):

> _Short answer: It's a known issue. Some people describe you can open some ports to fix it, for others it doesn't work. Since it's not affecting your gameplay ignoring it is the best way to go._

**Comment by mathielo** [comment]
Hey @acklackl this might be coming in late, but I actually managed to fix the ping shown as `???` issue. It was actually a very silly mistake on the ports setup as you can see in the fix 3a18393.

I knew this was a very old and known issue with dedicated servers (even before starting this project), so didn't spend too much time on the issue as it doesn't affect anything else than the ping number display. However just recently I noticed that the port setup looked odd, so I fixed it and... BAM! :boom:  Ping was being shown correctly on server list :sweat_smile:
