### ISSUE TITLE
Reset world by seed

### ISSUE THREAD

**Issue by fateseekers** [mathielo/dst-dedicated-server#36]
Hello, how can I reset world and generate it by current seed?

**Comment by mathielo** [comment]
Apparently this can only be done [with mods](https://www.reddit.com/r/dontstarve/comments/ktm3fa/comment/gpv5kts/?utm_source=share&utm_medium=web2x&context=3). See this [thread in Klei's Forums](https://forums.kleientertainment.com/forums/topic/112139-world-seeds-mod-generate-worlds-with-custom-world-seeds/) for further details!
