### ISSUE TITLE
Disable caves

### ISSUE THREAD

**Issue by vfsoraki** [mathielo/dst-dedicated-server#39]
Is it enough to disable the caves container in docker composer file? Or some configuration needs to change too?

**Comment by mathielo** [comment]
I never tried to generate the world without caves to be honest 🤔 Did you try it? If so, how did it go?

**Comment by vfsoraki** [comment]
I think it works. I didn’t test it completely, but it seemed I can play.

We reverted to with caves pretty soon after that.

**Comment by mathielo** [comment]
Alrighty :) If you come to test it in full please also feel free to PR documentation updates on how to do it! 💡
